import Sidebar from "../components/AdminDashboad/SideBar/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div style={{display:"flex"}}>
        <Sidebar/>
        {children}
        </div>
      </body>
    </html>
  );
}
